# -*- coding: utf-8 -*-
"""Introdução ao Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/140fmkJ7BGe4evYCCaSWsEVhbpZftkdRr
"""

import pandas as pd
uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
dados = pd.read_csv(uri)
dados.head()

mapa={
    "home":"principal",
    "how_it_works":"como_funciona",
    "contact":"contato",
    "bought":"comprado"
}
dados=dados.rename(columns=mapa)

x=dados[["principal","como_funciona","contato"]]
y=dados["comprado"]
y.head()

y

x

dados.shape

treino_x=x[:75]
treino_y=y[:75]

teste_x=x[75:]
teste_y=y[75:]

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo=LinearSVC()
modelo.fit(treino_x,treino_y)
previsoes=modelo.predict(teste_x)

taxa_acerto=accuracy_score(teste_y,previsoes)

print("A acurácia foi de %.2f%%" % (100*taxa_acerto))

from sklearn.model_selection import train_test_split

treino_x, teste_x, treino_y,teste_y=train_test_split(x,y,test_size=0.25)

import pandas as pd
uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
dados = pd.read_csv(uri)
dados.head()
rom sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
SEED=20

treino_x, teste_x, treino_y,teste_y = train_test_split(
    x,
    y,
    random_state=SEED,
    test_size=0.25,
    stratify=y)


modelo=LinearSVC()
modelo.fit(treino_x,treino_y)
previsoes=modelo.predict(teste_x)

taxa_acerto=accuracy_score(teste_y,previsoes)

print("A acurácia foi de %.2f%%" % (100*taxa_acerto))

teste_y.value_counts()

treino_y.value_counts()

modelo.predict([[1,0,1]])



"""# Nova seção"""

